### PR TITLE
update recommended atom packages. Added a link to script

### PR DESCRIPTION
**Pull request by JarLowrey**
https://github.com/HiFaraz/node-playbook/issues/9

### CODE REVIEW

**Comment by HiFaraz** [comment]
This is awesome, thank you so much!

How would I run the script? In the terminal?

**Comment by JarLowrey** [comment]
Yeah on linux you'd download the file and run atom_packages.sh

IDK how Windows does it

**Comment by HiFaraz** [comment]
I think you can run it on Windows too with the sh command.

Regardless, how about you make in an npm package that runs the shell script? Then we can add that to the playbook. The package can run the script on install and never be needed again. I think that's a way easier solution.

Thoughts?

**Comment by JarLowrey** [comment]
IDK I think an NPM package might be a bit overkill to just run these few lines. If you want to then feel free though!

**Comment by HiFaraz** [comment]
You mind if I go ahead and create it? Nearly done actually.

**Comment by JarLowrey** [comment]
Haha nope, go for it. Probably a good idea now that I think about it. Glad you pushed for it!

**Comment by HiFaraz** [comment]
Can you test it out please? https://www.npmjs.com/package/atom-starter-pack

**Comment by HiFaraz** [comment]
Hey, can you test it out please? Try Option 1 from here:

https://www.npmjs.com/package/atom-starter-pack

**Comment by JarLowrey** [comment]
Installing your Atom starter pack
sh: 1: installer.sh: not found
npm WARN aaa No description
npm WARN aaa No repository field.
npm WARN aaa No license field.
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "atom-starter-pack"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! atom-starter-pack@0.1.8-alpha preinstall: `echo Installing your Atom starter pack && installer.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the atom-starter-pack@0.1.8-alpha preinstall script 'echo Installing your Atom starter pack && installer.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-starter-pack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo Installing your Atom starter pack && installer.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-starter-pack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-starter-pack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/james/aaa/npm-debug.log

**Comment by JarLowrey** [comment]
Thanks for the shout-out!

**Comment by HiFaraz** [comment]
No worries man, you deserve it!

**Pull request merged**
