### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JarLowrey**

### CODE REVIEW

**Comment by HiFaraz** [comment]
Only HTML?

Also the menus must be different on Windows. Let's push them towards Ctrl/Cmd+Shift+P instead?

**Comment by JarLowrey** [comment]
HTML is just an example, it works for many languages. Ctrl Shit P can't take me to the settings unfortunately. Maybe just add a line above the package listing about how to get to the settings, and ignore this PR.

**Comment by HiFaraz** [comment]
Does Ctrl/Cmd+comma work to bring up settings for you?

**Comment by JarLowrey** [comment]
Yes!

**Comment by HiFaraz** [comment]
Can you send a new PR please with Ctrl/Cmd+comma?

Also can you not limit it to HTML? The original set was a good starter set (no decision making).

**Comment by JarLowrey** [comment]
To beautify you need to do it manually each time, or manually select each language it will run on upon saving.

**Comment by HiFaraz** [comment]
Lets maintain Beautify on Save for each language that is currently in the playbook.

**Pull request closed without merging**
